stages:
  - test
  - build
  - deploy

default:
  image: node:latest

unit-test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    name: "dnt-roster-test-coverage-$CI_COMMIT_SHORT_SHA"
    paths:
      - coverage/
    when: always

build-app:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    name: "dnt-roster-$CI_COMMIT_SHORT_SHA"
    paths:
      - "build/"

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

build-container-image:
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  stage: deploy
  script:
    - until docker info; do sleep 1; done
    - docker login --username=$HARBOR_USERNAME --password=$HARBOR_PASSWORD $HARBOR_URL
    - docker build -t $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:$CI_COMMIT_SHORT_SHA -t $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:latest .
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:$CI_COMMIT_SHORT_SHA
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:latest