stages:
  - test
  - build
  - deploy

default:
  image: node:latest
  before_script:
    - npm install

unit-test:
  stage: test
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    name: "dnt-roster-test-coverage-$CI_COMMIT_SHORT_SHA"
    paths:
      - coverage/
    when: always

build-app:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "dnt-roster-$CI_COMMIT_SHORT_SHA"
    paths:
      - "build/"

build-container-image:
  image: docker:latest
  stage: deploy
  script:
    - docker build -t harbor.nwallace.io/home-server/dnt-roster:$CI_COMMIT_SHORT_SHA
    - docker push harbor.nwallace.io/home-server/dnt-roster:$CI_COMMIT_SHORT_SHA