stages:
  - test
  - build
  - deploy

default:
  image: node:latest

unit-test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    name: "dnt-roster-test-coverage-$CI_COMMIT_SHORT_SHA"
    paths:
      - coverage/
    when: always

build-app:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    name: "dnt-roster-$CI_COMMIT_SHORT_SHA"
    paths:
      - "build/"

build-container-image:
  image: docker::24.0.7
  services:
    - docker:24.0.7-dind
  stage: deploy
  script:
    - docker build -t $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:$CI_COMMIT_SHORT_SHA .
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:$CI_COMMIT_SHORT_SHA