stages:
- pre
- test
- build
- build-container

default:
  image: node:latest
  cache:
    key: node_modules
    paths:
    - "node_modules"
    policy: pull

pre:
  stage: pre
  script:
  - npm ci
  cache:
    key: node_modules
    paths:
    - "node_modules"

test:
  stage: test
  script:
  - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

build-app:
  stage: build
  script:
  - npm run build
  artifacts:
    name: "dnt-roster-$CI_COMMIT_SHORT_SHA"
    paths:
    - "build/"
    expire_in: 600 seconds

build-container:
  image: docker:24.0.7
  cache: {}
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
  - docker:24.0.7-dind
  stage: build-container
  script:
  - until docker info; do sleep 1; done
  - docker login --username=$HARBOR_USERNAME --password=$HARBOR_PASSWORD $HARBOR_URL
  - docker build -t $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:$CI_COMMIT_SHORT_SHA -t $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster:latest .
  - docker push -a $HARBOR_HOST/$HARBOR_PROJECT/dnt-roster
