stages:
  - test
  - build

default:
  image: node:latest
  before_script:
    - npm install

unit-test:
  stage: test
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always

build-artifact:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "dnt-roster-{$CI_COMMIT_SHORT_SHA}"
    paths:
      - "build/"
