# production environment
FROM node:current-alpine3.15
WORKDIR /home/node/app
COPY package*.json ./
COPY server ./
COPY certificates/client-cert.pem ./
COPY certificates/client-key.pem ./
COPY certificates/ca-bundle.pem ./
RUN npm install
EXPOSE 3001
CMD ["node", "server.js"]
